export const endpoints = {
  health: "/health/",
  auth: {
    requestOtp: "/auth/request-otp",
    verifyOtp: "/auth/verify-otp",
    me: "/auth/me",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
  },
  user: {
    me: "/user/me",
    addressOptions: "/user/address-options",
    addressSuburbs: "/user/address-suburbs",
    checkAddressLocality: "/user/address-locality/check",
    addresses: "/user/addresses",
    address: (addressId: string) => `/user/addresses/${addressId}`,
    setDefaultAddress: (addressId: string) => `/user/addresses/${addressId}/default`,
  },
  catalog: {
    options: "/catalog/options",
    shrimp: "/catalog/shrimp",
    shrimpDetail: (shrimpId: string) => `/catalog/shrimp/${shrimpId}`,
    shrimpDetailBySlug: (slug: string) => `/catalog/shrimp/slug/${slug}`,
  },
  ownerCatalog: {
    options: "/owner/catalog/options",
    shrimp: "/owner/catalog/shrimp",
    shrimpDetail: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}`,
    deleteShrimp: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}`,
    activateShrimp: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}/activate`,
    deactivateShrimp: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}/deactivate`,
    variants: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}/variants`,
    variant: (shrimpId: string, variantId: string) =>
      `/owner/catalog/shrimp/${shrimpId}/variants/${variantId}`,
    careParameter: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}/care-parameter`,
    presignImage: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}/images/presign`,
    images: (shrimpId: string) => `/owner/catalog/shrimp/${shrimpId}/images`,
    image: (shrimpId: string, imageId: string) =>
      `/owner/catalog/shrimp/${shrimpId}/images/${imageId}`,
  },
  ownerUsers: {
    users: "/owner/users",
    user: (userId: string) => `/owner/users/${userId}`,
    activate: (userId: string) => `/owner/users/${userId}/activate`,
    deactivate: (userId: string) => `/owner/users/${userId}/deactivate`,
    role: (userId: string) => `/owner/users/${userId}/role`,
  },
  orders: {
    orders: "/orders",
    checkout: "/orders/checkout",
    paymentSession: (sessionId: string) => `/orders/payment-session/${sessionId}`,
    order: (orderId: string) => `/orders/${orderId}`,
    continuePayment: (orderId: string) => `/orders/${orderId}/continue-payment`,
    cancel: (orderId: string) => `/orders/${orderId}/cancel`,
  },
  ownerOrders: {
    orders: "/owner/orders",
    order: (orderId: string) => `/owner/orders/${orderId}`,
    status: (orderId: string) => `/owner/orders/${orderId}/status`,
  },
  ownerNotifications: {
    notifications: "/owner/notifications",
    read: (notificationId: string) => `/owner/notifications/${notificationId}/read`,
    readAll: "/owner/notifications/read-all",
    ws: "/owner/notifications/ws",
  },
  products: "/products",
} as const;
